---
- name: Ejecuta Jenkins OpenShift CICD-ARO
  hosts: localhost

  tasks:
    - name: echo ejecución API
      debug: msg="Iniciando ejecución API-Jenkins-OpenShift-CI\CD-ARO"
    - name: Llamado a API
      uri:
        url: "https://jenkins-cicd.apps.f6115a399213483d96ac.eastus.azmosa.io/job/cicd/job/cicd-tasks-pipeline/buildWithParameters?token=975317"
        method: GET
        user: "javier.perezsan@imss.gob.mx-admin-edit-view"
        password: "115a6d69490ef2001f2e046c25e363cefa"
        force_basic_auth: yes
        status_code: 200
        validate_certs: no
        body_format: json